// Code generated by Fern. DO NOT EDIT.

package client

import (
	annotationqueues "github.com/corysm1th/langfuse-go/annotationqueues"
	blobstorageintegrations "github.com/corysm1th/langfuse-go/blobstorageintegrations"
	comments "github.com/corysm1th/langfuse-go/comments"
	core "github.com/corysm1th/langfuse-go/core"
	datasetitems "github.com/corysm1th/langfuse-go/datasetitems"
	datasetrunitems "github.com/corysm1th/langfuse-go/datasetrunitems"
	datasets "github.com/corysm1th/langfuse-go/datasets"
	health "github.com/corysm1th/langfuse-go/health"
	ingestion "github.com/corysm1th/langfuse-go/ingestion"
	internal "github.com/corysm1th/langfuse-go/internal"
	legacymetricsv1 "github.com/corysm1th/langfuse-go/legacymetricsv1"
	legacyobservationsv1 "github.com/corysm1th/langfuse-go/legacyobservationsv1"
	legacyscorev1 "github.com/corysm1th/langfuse-go/legacyscorev1"
	llmconnections "github.com/corysm1th/langfuse-go/llmconnections"
	media "github.com/corysm1th/langfuse-go/media"
	metrics "github.com/corysm1th/langfuse-go/metrics"
	models "github.com/corysm1th/langfuse-go/models"
	observations "github.com/corysm1th/langfuse-go/observations"
	opentelemetry "github.com/corysm1th/langfuse-go/opentelemetry"
	option "github.com/corysm1th/langfuse-go/option"
	organizations "github.com/corysm1th/langfuse-go/organizations"
	projects "github.com/corysm1th/langfuse-go/projects"
	prompts "github.com/corysm1th/langfuse-go/prompts"
	promptversion "github.com/corysm1th/langfuse-go/promptversion"
	scim "github.com/corysm1th/langfuse-go/scim"
	scoreconfigs "github.com/corysm1th/langfuse-go/scoreconfigs"
	scores "github.com/corysm1th/langfuse-go/scores"
	sessions "github.com/corysm1th/langfuse-go/sessions"
	trace "github.com/corysm1th/langfuse-go/trace"
	unstableevaluationrules "github.com/corysm1th/langfuse-go/unstableevaluationrules"
	unstableevaluators "github.com/corysm1th/langfuse-go/unstableevaluators"
)

type LangfuseClient struct {
	Annotationqueues        *annotationqueues.Client
	Blobstorageintegrations *blobstorageintegrations.Client
	Comments                *comments.Client
	Datasetitems            *datasetitems.Client
	Datasetrunitems         *datasetrunitems.Client
	Datasets                *datasets.Client
	Health                  *health.Client
	Ingestion               *ingestion.Client
	LegacyMetricsV1         *legacymetricsv1.Client
	LegacyObservationsV1    *legacyobservationsv1.Client
	LegacyScoreV1           *legacyscorev1.Client
	Llmconnections          *llmconnections.Client
	Media                   *media.Client
	Metrics                 *metrics.Client
	Models                  *models.Client
	Observations            *observations.Client
	Opentelemetry           *opentelemetry.Client
	Organizations           *organizations.Client
	Projects                *projects.Client
	Promptversion           *promptversion.Client
	Prompts                 *prompts.Client
	SCIM                    *scim.Client
	Scoreconfigs            *scoreconfigs.Client
	Scores                  *scores.Client
	Sessions                *sessions.Client
	Trace                   *trace.Client
	UnstableEvaluationRules *unstableevaluationrules.Client
	UnstableEvaluators      *unstableevaluators.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewLangfuseClient(opts ...option.RequestOption) *LangfuseClient {
	options := core.NewRequestOptions(opts...)
	return &LangfuseClient{
		Annotationqueues:        annotationqueues.NewClient(options),
		Blobstorageintegrations: blobstorageintegrations.NewClient(options),
		Comments:                comments.NewClient(options),
		Datasetitems:            datasetitems.NewClient(options),
		Datasetrunitems:         datasetrunitems.NewClient(options),
		Datasets:                datasets.NewClient(options),
		Health:                  health.NewClient(options),
		Ingestion:               ingestion.NewClient(options),
		LegacyMetricsV1:         legacymetricsv1.NewClient(options),
		LegacyObservationsV1:    legacyobservationsv1.NewClient(options),
		LegacyScoreV1:           legacyscorev1.NewClient(options),
		Llmconnections:          llmconnections.NewClient(options),
		Media:                   media.NewClient(options),
		Metrics:                 metrics.NewClient(options),
		Models:                  models.NewClient(options),
		Observations:            observations.NewClient(options),
		Opentelemetry:           opentelemetry.NewClient(options),
		Organizations:           organizations.NewClient(options),
		Projects:                projects.NewClient(options),
		Promptversion:           promptversion.NewClient(options),
		Prompts:                 prompts.NewClient(options),
		SCIM:                    scim.NewClient(options),
		Scoreconfigs:            scoreconfigs.NewClient(options),
		Scores:                  scores.NewClient(options),
		Sessions:                sessions.NewClient(options),
		Trace:                   trace.NewClient(options),
		UnstableEvaluationRules: unstableevaluationrules.NewClient(options),
		UnstableEvaluators:      unstableevaluators.NewClient(options),
		options:                 options,
		baseURL:                 options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
