// Code generated by Fern. DO NOT EDIT.

package langfuse

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/corysm1th/langfuse-go/internal"
	big "math/big"
	time "time"
)

var (
	legacyObservationsV1GetRequestFieldObservationID = big.NewInt(1 << 0)
)

type LegacyObservationsV1GetRequest struct {
	// The unique langfuse identifier of an observation, can be an event, span or generation
	ObservationID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LegacyObservationsV1GetRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetObservationID sets the ObservationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetRequest) SetObservationID(observationID string) {
	l.ObservationID = observationID
	l.require(legacyObservationsV1GetRequestFieldObservationID)
}

var (
	legacyObservationsV1GetManyRequestFieldPage                = big.NewInt(1 << 0)
	legacyObservationsV1GetManyRequestFieldLimit               = big.NewInt(1 << 1)
	legacyObservationsV1GetManyRequestFieldName                = big.NewInt(1 << 2)
	legacyObservationsV1GetManyRequestFieldUserID              = big.NewInt(1 << 3)
	legacyObservationsV1GetManyRequestFieldType                = big.NewInt(1 << 4)
	legacyObservationsV1GetManyRequestFieldTraceID             = big.NewInt(1 << 5)
	legacyObservationsV1GetManyRequestFieldLevel               = big.NewInt(1 << 6)
	legacyObservationsV1GetManyRequestFieldParentObservationID = big.NewInt(1 << 7)
	legacyObservationsV1GetManyRequestFieldEnvironment         = big.NewInt(1 << 8)
	legacyObservationsV1GetManyRequestFieldFromStartTime       = big.NewInt(1 << 9)
	legacyObservationsV1GetManyRequestFieldToStartTime         = big.NewInt(1 << 10)
	legacyObservationsV1GetManyRequestFieldVersion             = big.NewInt(1 << 11)
	legacyObservationsV1GetManyRequestFieldFilter              = big.NewInt(1 << 12)
)

type LegacyObservationsV1GetManyRequest struct {
	// Page number, starts at 1.
	Page *int `json:"-" url:"page,omitempty"`
	// Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit.
	Limit   *int    `json:"-" url:"limit,omitempty"`
	Name    *string `json:"-" url:"name,omitempty"`
	UserID  *string `json:"-" url:"userId,omitempty"`
	Type    *string `json:"-" url:"type,omitempty"`
	TraceID *string `json:"-" url:"traceId,omitempty"`
	// Optional filter for observations with a specific level (e.g. "DEBUG", "DEFAULT", "WARNING", "ERROR").
	Level               *ObservationLevel `json:"-" url:"level,omitempty"`
	ParentObservationID *string           `json:"-" url:"parentObservationId,omitempty"`
	// Optional filter for observations where the environment is one of the provided values.
	Environment []*string `json:"-" url:"environment,omitempty"`
	// Retrieve only observations with a start_time on or after this datetime (ISO 8601).
	FromStartTime *time.Time `json:"-" url:"fromStartTime,omitempty"`
	// Retrieve only observations with a start_time before this datetime (ISO 8601).
	ToStartTime *time.Time `json:"-" url:"toStartTime,omitempty"`
	// Optional filter to only include observations with a certain version.
	Version *string `json:"-" url:"version,omitempty"`
	// JSON string containing an array of filter conditions. When provided, this takes precedence over query parameter filters (userId, name, type, level, environment, fromStartTime, ...).
	//
	// ## Filter Structure
	// Each filter condition has the following structure:
	// ```json
	// [
	//
	//	{
	//	  "type": string,           // Required. One of: "datetime", "string", "number", "stringOptions", "categoryOptions", "arrayOptions", "stringObject", "numberObject", "boolean", "null"
	//	  "column": string,         // Required. Column to filter on (see available columns below)
	//	  "operator": string,       // Required. Operator based on type:
	//	                            // - datetime: ">", "<", ">=", "<="
	//	                            // - string: "=", "contains", "does not contain", "starts with", "ends with"
	//	                            // - stringOptions: "any of", "none of"
	//	                            // - categoryOptions: "any of", "none of"
	//	                            // - arrayOptions: "any of", "none of", "all of"
	//	                            // - number: "=", ">", "<", ">=", "<="
	//	                            // - stringObject: "=", "contains", "does not contain", "starts with", "ends with"
	//	                            // - numberObject: "=", ">", "<", ">=", "<="
	//	                            // - boolean: "=", "<>"
	//	                            // - null: "is null", "is not null"
	//	  "value": any,             // Required (except for null type). Value to compare against. Type depends on filter type
	//	  "key": string             // Required only for stringObject, numberObject, and categoryOptions types when filtering on nested fields like metadata
	//	}
	//
	// ]
	// ```
	//
	// ## Available Columns
	//
	// ### Core Observation Fields
	// - `id` (string) - Observation ID
	// - `type` (string) - Observation type (SPAN, GENERATION, EVENT)
	// - `name` (string) - Observation name
	// - `traceId` (string) - Associated trace ID
	// - `startTime` (datetime) - Observation start time
	// - `endTime` (datetime) - Observation end time
	// - `environment` (string) - Environment tag
	// - `level` (string) - Log level (DEBUG, DEFAULT, WARNING, ERROR)
	// - `statusMessage` (string) - Status message
	// - `version` (string) - Version tag
	//
	// ### Performance Metrics
	// - `latency` (number) - Latency in seconds (calculated: end_time - start_time)
	// - `timeToFirstToken` (number) - Time to first token in seconds
	// - `tokensPerSecond` (number) - Output tokens per second
	//
	// ### Token Usage
	// - `inputTokens` (number) - Number of input tokens
	// - `outputTokens` (number) - Number of output tokens
	// - `totalTokens` (number) - Total tokens (alias: `tokens`)
	//
	// ### Cost Metrics
	// - `inputCost` (number) - Input cost in USD
	// - `outputCost` (number) - Output cost in USD
	// - `totalCost` (number) - Total cost in USD
	//
	// ### Model Information
	// - `model` (string) - Provided model name
	// - `promptName` (string) - Associated prompt name
	// - `promptVersion` (number) - Associated prompt version
	//
	// ### Structured Data
	// - `metadata` (stringObject/numberObject/categoryOptions) - Metadata key-value pairs. Use `key` parameter to filter on specific metadata keys.
	//
	// ### Associated Trace Fields (requires join with traces table)
	// - `userId` (string) - User ID from associated trace
	// - `traceName` (string) - Name from associated trace
	// - `traceEnvironment` (string) - Environment from associated trace
	// - `traceTags` (arrayOptions) - Tags from associated trace
	//
	// ## Filter Examples
	// ```json
	// [
	//
	//	{
	//	  "type": "string",
	//	  "column": "type",
	//	  "operator": "=",
	//	  "value": "GENERATION"
	//	},
	//	{
	//	  "type": "number",
	//	  "column": "latency",
	//	  "operator": ">=",
	//	  "value": 2.5
	//	},
	//	{
	//	  "type": "stringObject",
	//	  "column": "metadata",
	//	  "key": "environment",
	//	  "operator": "=",
	//	  "value": "production"
	//	}
	//
	// ]
	// ```
	Filter *string `json:"-" url:"filter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LegacyObservationsV1GetManyRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetPage(page *int) {
	l.Page = page
	l.require(legacyObservationsV1GetManyRequestFieldPage)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(legacyObservationsV1GetManyRequestFieldLimit)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetName(name *string) {
	l.Name = name
	l.require(legacyObservationsV1GetManyRequestFieldName)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetUserID(userID *string) {
	l.UserID = userID
	l.require(legacyObservationsV1GetManyRequestFieldUserID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetType(type_ *string) {
	l.Type = type_
	l.require(legacyObservationsV1GetManyRequestFieldType)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetTraceID(traceID *string) {
	l.TraceID = traceID
	l.require(legacyObservationsV1GetManyRequestFieldTraceID)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetLevel(level *ObservationLevel) {
	l.Level = level
	l.require(legacyObservationsV1GetManyRequestFieldLevel)
}

// SetParentObservationID sets the ParentObservationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetParentObservationID(parentObservationID *string) {
	l.ParentObservationID = parentObservationID
	l.require(legacyObservationsV1GetManyRequestFieldParentObservationID)
}

// SetEnvironment sets the Environment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetEnvironment(environment []*string) {
	l.Environment = environment
	l.require(legacyObservationsV1GetManyRequestFieldEnvironment)
}

// SetFromStartTime sets the FromStartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetFromStartTime(fromStartTime *time.Time) {
	l.FromStartTime = fromStartTime
	l.require(legacyObservationsV1GetManyRequestFieldFromStartTime)
}

// SetToStartTime sets the ToStartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetToStartTime(toStartTime *time.Time) {
	l.ToStartTime = toStartTime
	l.require(legacyObservationsV1GetManyRequestFieldToStartTime)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetVersion(version *string) {
	l.Version = version
	l.require(legacyObservationsV1GetManyRequestFieldVersion)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsV1GetManyRequest) SetFilter(filter *string) {
	l.Filter = filter
	l.require(legacyObservationsV1GetManyRequestFieldFilter)
}

var (
	legacyObservationsViewsFieldData = big.NewInt(1 << 0)
	legacyObservationsViewsFieldMeta = big.NewInt(1 << 1)
)

type LegacyObservationsViews struct {
	Data []*ObservationsView `json:"data" url:"data"`
	Meta *UtilsMetaResponse  `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LegacyObservationsViews) GetData() []*ObservationsView {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *LegacyObservationsViews) GetMeta() *UtilsMetaResponse {
	if l == nil {
		return nil
	}
	return l.Meta
}

func (l *LegacyObservationsViews) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LegacyObservationsViews) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsViews) SetData(data []*ObservationsView) {
	l.Data = data
	l.require(legacyObservationsViewsFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyObservationsViews) SetMeta(meta *UtilsMetaResponse) {
	l.Meta = meta
	l.require(legacyObservationsViewsFieldMeta)
}

func (l *LegacyObservationsViews) UnmarshalJSON(data []byte) error {
	type unmarshaler LegacyObservationsViews
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LegacyObservationsViews(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LegacyObservationsViews) MarshalJSON() ([]byte, error) {
	type embed LegacyObservationsViews
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LegacyObservationsViews) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
