// Code generated by Fern. DO NOT EDIT.

package langfuse

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/corysm1th/langfuse-go/internal"
	big "math/big"
)

var (
	legacyMetricsV1MetricsRequestFieldQuery = big.NewInt(1 << 0)
)

type LegacyMetricsV1MetricsRequest struct {
	// JSON string containing the query parameters with the following structure:
	// ```json
	//
	//	{
	//	  "view": string,           // Required. One of "traces", "observations", "scores-numeric", "scores-categorical"
	//	  "dimensions": [           // Optional. Default: []
	//	    {
	//	      "field": string       // Field to group by, e.g. "name", "userId", "sessionId"
	//	    }
	//	  ],
	//	  "metrics": [              // Required. At least one metric must be provided
	//	    {
	//	      "measure": string,    // What to measure, e.g. "count", "latency", "value"
	//	      "aggregation": string // How to aggregate, e.g. "count", "sum", "avg", "p95", "histogram"
	//	    }
	//	  ],
	//	  "filters": [              // Optional. Default: []
	//	    {
	//	      "column": string,     // Column to filter on
	//	      "operator": string,   // Operator, e.g. "=", ">", "<", "contains"
	//	      "value": any,         // Value to compare against
	//	      "type": string,       // Data type, e.g. "string", "number", "stringObject"
	//	      "key": string         // Required only when filtering on metadata
	//	    }
	//	  ],
	//	  "timeDimension": {        // Optional. Default: null. If provided, results will be grouped by time
	//	    "granularity": string   // One of "minute", "hour", "day", "week", "month", "auto"
	//	  },
	//	  "fromTimestamp": string,  // Required. ISO datetime string for start of time range
	//	  "toTimestamp": string,    // Required. ISO datetime string for end of time range
	//	  "orderBy": [              // Optional. Default: null
	//	    {
	//	      "field": string,      // Field to order by
	//	      "direction": string   // "asc" or "desc"
	//	    }
	//	  ],
	//	  "config": {               // Optional. Query-specific configuration
	//	    "bins": number,         // Optional. Number of bins for histogram (1-100), default: 10
	//	    "row_limit": number     // Optional. Row limit for results (1-1000)
	//	  }
	//	}
	//
	// ```
	Query string `json:"-" url:"query"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LegacyMetricsV1MetricsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyMetricsV1MetricsRequest) SetQuery(query string) {
	l.Query = query
	l.require(legacyMetricsV1MetricsRequestFieldQuery)
}

var (
	legacyMetricsResponseFieldData = big.NewInt(1 << 0)
)

type LegacyMetricsResponse struct {
	// The metrics data. Each item in the list contains the metric values and dimensions requested in the query.
	// Format varies based on the query parameters.
	// Histograms will return an array with [lower, upper, height] tuples.
	Data []map[string]any `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LegacyMetricsResponse) GetData() []map[string]any {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *LegacyMetricsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LegacyMetricsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LegacyMetricsResponse) SetData(data []map[string]any) {
	l.Data = data
	l.require(legacyMetricsResponseFieldData)
}

func (l *LegacyMetricsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LegacyMetricsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LegacyMetricsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LegacyMetricsResponse) MarshalJSON() ([]byte, error) {
	type embed LegacyMetricsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LegacyMetricsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
