// Code generated by Fern. DO NOT EDIT.

package langfuse

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersMediaGetRequest(t *testing.T) {
	t.Run("SetMediaID", func(t *testing.T) {
		obj := &MediaGetRequest{}
		var fernTestValueMediaID string
		obj.SetMediaID(fernTestValueMediaID)
		assert.Equal(t, fernTestValueMediaID, obj.MediaID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitMediaGetRequest(t *testing.T) {
	t.Run("SetMediaID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MediaGetRequest{}
		var fernTestValueMediaID string

		// Act
		obj.SetMediaID(fernTestValueMediaID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetMediaUploadURLRequest(t *testing.T) {
	t.Run("SetTraceID", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueTraceID string
		obj.SetTraceID(fernTestValueTraceID)
		assert.Equal(t, fernTestValueTraceID, obj.TraceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetObservationID", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueObservationID *string
		obj.SetObservationID(fernTestValueObservationID)
		assert.Equal(t, fernTestValueObservationID, obj.ObservationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContentType", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueContentType MediaContentType
		obj.SetContentType(fernTestValueContentType)
		assert.Equal(t, fernTestValueContentType, obj.ContentType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContentLength", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueContentLength int
		obj.SetContentLength(fernTestValueContentLength)
		assert.Equal(t, fernTestValueContentLength, obj.ContentLength)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSha256Hash", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueSha256Hash string
		obj.SetSha256Hash(fernTestValueSha256Hash)
		assert.Equal(t, fernTestValueSha256Hash, obj.Sha256Hash)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetField", func(t *testing.T) {
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueField string
		obj.SetField(fernTestValueField)
		assert.Equal(t, fernTestValueField, obj.Field)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetMediaUploadURLRequest(t *testing.T) {
	t.Run("SetTraceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueTraceID string

		// Act
		obj.SetTraceID(fernTestValueTraceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetObservationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueObservationID *string

		// Act
		obj.SetObservationID(fernTestValueObservationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContentType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueContentType MediaContentType

		// Act
		obj.SetContentType(fernTestValueContentType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContentLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueContentLength int

		// Act
		obj.SetContentLength(fernTestValueContentLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSha256Hash_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueSha256Hash string

		// Act
		obj.SetSha256Hash(fernTestValueSha256Hash)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetField_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLRequest{}
		var fernTestValueField string

		// Act
		obj.SetField(fernTestValueField)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPatchMediaBody(t *testing.T) {
	t.Run("SetMediaID", func(t *testing.T) {
		obj := &PatchMediaBody{}
		var fernTestValueMediaID string
		obj.SetMediaID(fernTestValueMediaID)
		assert.Equal(t, fernTestValueMediaID, obj.MediaID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadedAt", func(t *testing.T) {
		obj := &PatchMediaBody{}
		var fernTestValueUploadedAt time.Time
		obj.SetUploadedAt(fernTestValueUploadedAt)
		assert.Equal(t, fernTestValueUploadedAt, obj.UploadedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadHTTPStatus", func(t *testing.T) {
		obj := &PatchMediaBody{}
		var fernTestValueUploadHTTPStatus int
		obj.SetUploadHTTPStatus(fernTestValueUploadHTTPStatus)
		assert.Equal(t, fernTestValueUploadHTTPStatus, obj.UploadHTTPStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadHTTPError", func(t *testing.T) {
		obj := &PatchMediaBody{}
		var fernTestValueUploadHTTPError *string
		obj.SetUploadHTTPError(fernTestValueUploadHTTPError)
		assert.Equal(t, fernTestValueUploadHTTPError, obj.UploadHTTPError)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadTimeMs", func(t *testing.T) {
		obj := &PatchMediaBody{}
		var fernTestValueUploadTimeMs *int
		obj.SetUploadTimeMs(fernTestValueUploadTimeMs)
		assert.Equal(t, fernTestValueUploadTimeMs, obj.UploadTimeMs)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPatchMediaBody(t *testing.T) {
	t.Run("SetMediaID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PatchMediaBody{}
		var fernTestValueMediaID string

		// Act
		obj.SetMediaID(fernTestValueMediaID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PatchMediaBody{}
		var fernTestValueUploadedAt time.Time

		// Act
		obj.SetUploadedAt(fernTestValueUploadedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadHTTPStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PatchMediaBody{}
		var fernTestValueUploadHTTPStatus int

		// Act
		obj.SetUploadHTTPStatus(fernTestValueUploadHTTPStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadHTTPError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PatchMediaBody{}
		var fernTestValueUploadHTTPError *string

		// Act
		obj.SetUploadHTTPError(fernTestValueUploadHTTPError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadTimeMs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PatchMediaBody{}
		var fernTestValueUploadTimeMs *int

		// Act
		obj.SetUploadTimeMs(fernTestValueUploadTimeMs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetMediaResponse(t *testing.T) {
	t.Run("SetMediaID", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueMediaID string
		obj.SetMediaID(fernTestValueMediaID)
		assert.Equal(t, fernTestValueMediaID, obj.MediaID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContentType", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueContentType string
		obj.SetContentType(fernTestValueContentType)
		assert.Equal(t, fernTestValueContentType, obj.ContentType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContentLength", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueContentLength int
		obj.SetContentLength(fernTestValueContentLength)
		assert.Equal(t, fernTestValueContentLength, obj.ContentLength)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUploadedAt", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueUploadedAt time.Time
		obj.SetUploadedAt(fernTestValueUploadedAt)
		assert.Equal(t, fernTestValueUploadedAt, obj.UploadedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetURL", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueURL string
		obj.SetURL(fernTestValueURL)
		assert.Equal(t, fernTestValueURL, obj.URL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetURLExpiry", func(t *testing.T) {
		obj := &GetMediaResponse{}
		var fernTestValueURLExpiry string
		obj.SetURLExpiry(fernTestValueURLExpiry)
		assert.Equal(t, fernTestValueURLExpiry, obj.URLExpiry)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetMediaResponse(t *testing.T) {
	t.Run("GetMediaID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected string
		obj.MediaID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMediaID(), "getter should return the property value")
	})

	t.Run("GetMediaID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMediaID() // Should return zero value
	})

	t.Run("GetContentType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected string
		obj.ContentType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetContentType(), "getter should return the property value")
	})

	t.Run("GetContentType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetContentType() // Should return zero value
	})

	t.Run("GetContentLength", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected int
		obj.ContentLength = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetContentLength(), "getter should return the property value")
	})

	t.Run("GetContentLength_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetContentLength() // Should return zero value
	})

	t.Run("GetUploadedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected time.Time
		obj.UploadedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUploadedAt(), "getter should return the property value")
	})

	t.Run("GetUploadedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUploadedAt() // Should return zero value
	})

	t.Run("GetURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected string
		obj.URL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURL(), "getter should return the property value")
	})

	t.Run("GetURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURL() // Should return zero value
	})

	t.Run("GetURLExpiry", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var expected string
		obj.URLExpiry = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetURLExpiry(), "getter should return the property value")
	})

	t.Run("GetURLExpiry_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetURLExpiry() // Should return zero value
	})

}

func TestSettersMarkExplicitGetMediaResponse(t *testing.T) {
	t.Run("SetMediaID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueMediaID string

		// Act
		obj.SetMediaID(fernTestValueMediaID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContentType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueContentType string

		// Act
		obj.SetContentType(fernTestValueContentType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContentLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueContentLength int

		// Act
		obj.SetContentLength(fernTestValueContentLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUploadedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueUploadedAt time.Time

		// Act
		obj.SetUploadedAt(fernTestValueUploadedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueURL string

		// Act
		obj.SetURL(fernTestValueURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetURLExpiry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}
		var fernTestValueURLExpiry string

		// Act
		obj.SetURLExpiry(fernTestValueURLExpiry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetMediaUploadURLResponse(t *testing.T) {
	t.Run("SetUploadURL", func(t *testing.T) {
		obj := &GetMediaUploadURLResponse{}
		var fernTestValueUploadURL *string
		obj.SetUploadURL(fernTestValueUploadURL)
		assert.Equal(t, fernTestValueUploadURL, obj.UploadURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMediaID", func(t *testing.T) {
		obj := &GetMediaUploadURLResponse{}
		var fernTestValueMediaID string
		obj.SetMediaID(fernTestValueMediaID)
		assert.Equal(t, fernTestValueMediaID, obj.MediaID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetMediaUploadURLResponse(t *testing.T) {
	t.Run("GetUploadURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}
		var expected *string
		obj.UploadURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUploadURL(), "getter should return the property value")
	})

	t.Run("GetUploadURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}
		obj.UploadURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetUploadURL(), "getter should return nil when property is nil")
	})

	t.Run("GetUploadURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaUploadURLResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUploadURL() // Should return zero value
	})

	t.Run("GetMediaID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}
		var expected string
		obj.MediaID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMediaID(), "getter should return the property value")
	})

	t.Run("GetMediaID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaUploadURLResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMediaID() // Should return zero value
	})

}

func TestSettersMarkExplicitGetMediaUploadURLResponse(t *testing.T) {
	t.Run("SetUploadURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}
		var fernTestValueUploadURL *string

		// Act
		obj.SetUploadURL(fernTestValueUploadURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMediaID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}
		var fernTestValueMediaID string

		// Act
		obj.SetMediaID(fernTestValueMediaID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGetMediaResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetMediaResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetMediaResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetMediaResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetMediaUploadURLResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMediaUploadURLResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetMediaUploadURLResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetMediaUploadURLResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetMediaUploadURLResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGetMediaResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetMediaResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetMediaUploadURLResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetMediaUploadURLResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaUploadURLResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumMediaContentType(t *testing.T) {
	t.Run("NewFromString_image_png", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/png")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/png"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_jpeg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/jpeg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/jpeg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_jpg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/jpg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/jpg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_webp", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/webp")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/webp"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_gif", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/gif")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/gif"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_svg+xml", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/svg+xml")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/svg+xml"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_tiff", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/tiff")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/tiff"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_bmp", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/bmp")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/bmp"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_avif", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/avif")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/avif"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_image_heic", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("image/heic")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("image/heic"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_mpeg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/mpeg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/mpeg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_mp3", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/mp3")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/mp3"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_wav", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/wav")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/wav"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_ogg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/ogg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/ogg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_oga", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/oga")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/oga"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_aac", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/aac")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/aac"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_mp4", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/mp4")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/mp4"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_flac", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/flac")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/flac"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_opus", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/opus")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/opus"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_audio_webm", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("audio/webm")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("audio/webm"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_mp4", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/mp4")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/mp4"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_webm", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/webm")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/webm"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_ogg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/ogg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/ogg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_mpeg", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/mpeg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/mpeg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_quicktime", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/quicktime")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/quicktime"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_x_msvideo", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/x-msvideo")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/x-msvideo"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_video_x_matroska", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("video/x-matroska")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("video/x-matroska"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_plain", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/plain")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/plain"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_html", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/html")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/html"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_css", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/css")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/css"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_csv", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/csv")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/csv"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_markdown", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/markdown")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/markdown"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_x_python", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/x-python")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/x-python"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_javascript", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/javascript")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/javascript"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_text_x_typescript", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("text/x-typescript")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("text/x-typescript"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_x_yaml", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/x-yaml")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/x-yaml"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_pdf", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/pdf")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/pdf"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_msword", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/msword")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/msword"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_vnd_ms_excel", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/vnd.ms-excel")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/vnd.ms-excel"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_vnd_openxmlformats_officedocument_spreadsheetml_sheet", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_zip", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/zip")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/zip"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_json", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/json")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/json"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_xml", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/xml")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/xml"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_octet_stream", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/octet-stream")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/octet-stream"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_vnd_openxmlformats_officedocument_wordprocessingml_document", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/vnd.openxmlformats-officedocument.wordprocessingml.document"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_vnd_openxmlformats_officedocument_presentationml_presentation", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/vnd.openxmlformats-officedocument.presentationml.presentation")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/vnd.openxmlformats-officedocument.presentationml.presentation"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_rtf", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/rtf")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/rtf"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_x_ndjson", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/x-ndjson")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/x-ndjson"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_vnd_apache_parquet", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/vnd.apache.parquet")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/vnd.apache.parquet"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_gzip", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/gzip")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/gzip"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_x_tar", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/x-tar")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/x-tar"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_application_x_7z_compressed", func(t *testing.T) {
		t.Parallel()
		val, err := NewMediaContentTypeFromString("application/x-7z-compressed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, MediaContentType("application/x-7z-compressed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewMediaContentTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewMediaContentTypeFromString("image/png")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesGetMediaResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetMediaResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetMediaUploadURLResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetMediaUploadURLResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMediaUploadURLResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
