// Code generated by Fern. DO NOT EDIT.

package langfuse

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/corysm1th/langfuse-go/internal"
	big "math/big"
	time "time"
)

var (
	observationsGetManyRequestFieldFields              = big.NewInt(1 << 0)
	observationsGetManyRequestFieldExpandMetadata      = big.NewInt(1 << 1)
	observationsGetManyRequestFieldLimit               = big.NewInt(1 << 2)
	observationsGetManyRequestFieldCursor              = big.NewInt(1 << 3)
	observationsGetManyRequestFieldParseIoAsJSON       = big.NewInt(1 << 4)
	observationsGetManyRequestFieldName                = big.NewInt(1 << 5)
	observationsGetManyRequestFieldUserID              = big.NewInt(1 << 6)
	observationsGetManyRequestFieldType                = big.NewInt(1 << 7)
	observationsGetManyRequestFieldTraceID             = big.NewInt(1 << 8)
	observationsGetManyRequestFieldLevel               = big.NewInt(1 << 9)
	observationsGetManyRequestFieldParentObservationID = big.NewInt(1 << 10)
	observationsGetManyRequestFieldEnvironment         = big.NewInt(1 << 11)
	observationsGetManyRequestFieldFromStartTime       = big.NewInt(1 << 12)
	observationsGetManyRequestFieldToStartTime         = big.NewInt(1 << 13)
	observationsGetManyRequestFieldVersion             = big.NewInt(1 << 14)
	observationsGetManyRequestFieldFilter              = big.NewInt(1 << 15)
)

type ObservationsGetManyRequest struct {
	// Comma-separated list of field groups to include in the response.
	// Available groups: core, basic, time, io, metadata, model, usage, prompt, metrics.
	// If not specified, `core` and `basic` field groups are returned.
	// Example: "basic,usage,model"
	Fields *string `json:"-" url:"fields,omitempty"`
	// Comma-separated list of metadata keys to return non-truncated.
	// By default, metadata values over 200 characters are truncated.
	// Use this parameter to retrieve full values for specific keys.
	// Example: "key1,key2"
	ExpandMetadata *string `json:"-" url:"expandMetadata,omitempty"`
	// Number of items to return per page. Maximum 1000, default 50.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Base64-encoded cursor for pagination. Use the cursor from the previous response to get the next page.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// **Deprecated.** Setting this to `true` will return a 400 error.
	// Input/output fields are always returned as raw strings.
	// Remove this parameter or set it to `false`.
	ParseIoAsJSON *bool   `json:"-" url:"parseIoAsJson,omitempty"`
	Name          *string `json:"-" url:"name,omitempty"`
	UserID        *string `json:"-" url:"userId,omitempty"`
	// Filter by observation type (e.g., "GENERATION", "SPAN", "EVENT", "AGENT", "TOOL", "CHAIN", "RETRIEVER", "EVALUATOR", "EMBEDDING", "GUARDRAIL")
	Type    *string `json:"-" url:"type,omitempty"`
	TraceID *string `json:"-" url:"traceId,omitempty"`
	// Optional filter for observations with a specific level (e.g. "DEBUG", "DEFAULT", "WARNING", "ERROR").
	Level               *ObservationLevel `json:"-" url:"level,omitempty"`
	ParentObservationID *string           `json:"-" url:"parentObservationId,omitempty"`
	// Optional filter for observations where the environment is one of the provided values.
	Environment []*string `json:"-" url:"environment,omitempty"`
	// Retrieve only observations with a start_time on or after this datetime (ISO 8601).
	FromStartTime *time.Time `json:"-" url:"fromStartTime,omitempty"`
	// Retrieve only observations with a start_time before this datetime (ISO 8601).
	ToStartTime *time.Time `json:"-" url:"toStartTime,omitempty"`
	// Optional filter to only include observations with a certain version.
	Version *string `json:"-" url:"version,omitempty"`
	// JSON string containing an array of filter conditions. When provided, this takes precedence over query parameter filters (userId, name, type, level, environment, fromStartTime, ...).
	//
	// ## Filter Structure
	// Each filter condition has the following structure:
	// ```json
	// [
	//
	//	{
	//	  "type": string,           // Required. One of: "datetime", "string", "number", "stringOptions", "categoryOptions", "arrayOptions", "stringObject", "numberObject", "boolean", "null"
	//	  "column": string,         // Required. Column to filter on (see available columns below)
	//	  "operator": string,       // Required. Operator based on type:
	//	                            // - datetime: ">", "<", ">=", "<="
	//	                            // - string: "=", "contains", "does not contain", "starts with", "ends with"
	//	                            // - stringOptions: "any of", "none of"
	//	                            // - categoryOptions: "any of", "none of"
	//	                            // - arrayOptions: "any of", "none of", "all of"
	//	                            // - number: "=", ">", "<", ">=", "<="
	//	                            // - stringObject: "=", "contains", "does not contain", "starts with", "ends with"
	//	                            // - numberObject: "=", ">", "<", ">=", "<="
	//	                            // - boolean: "=", "<>"
	//	                            // - null: "is null", "is not null"
	//	  "value": any,             // Required (except for null type). Value to compare against. Type depends on filter type
	//	  "key": string             // Required only for stringObject, numberObject, and categoryOptions types when filtering on nested fields like metadata
	//	}
	//
	// ]
	// ```
	//
	// ## Available Columns
	//
	// ### Core Observation Fields
	// - `id` (string) - Observation ID
	// - `type` (string) - Observation type (SPAN, GENERATION, EVENT)
	// - `name` (string) - Observation name
	// - `traceId` (string) - Associated trace ID
	// - `startTime` (datetime) - Observation start time
	// - `endTime` (datetime) - Observation end time
	// - `environment` (string) - Environment tag
	// - `level` (string) - Log level (DEBUG, DEFAULT, WARNING, ERROR)
	// - `statusMessage` (string) - Status message
	// - `version` (string) - Version tag
	// - `userId` (string) - User ID
	// - `sessionId` (string) - Session ID
	//
	// ### Trace-Related Fields
	// - `traceName` (string) - Name of the parent trace
	// - `traceTags` (arrayOptions) - Tags from the parent trace
	// - `tags` (arrayOptions) - Alias for traceTags
	//
	// ### Performance Metrics
	// - `latency` (number) - Latency in seconds (calculated: end_time - start_time)
	// - `timeToFirstToken` (number) - Time to first token in seconds
	// - `tokensPerSecond` (number) - Output tokens per second
	//
	// ### Token Usage
	// - `inputTokens` (number) - Number of input tokens
	// - `outputTokens` (number) - Number of output tokens
	// - `totalTokens` (number) - Total tokens (alias: `tokens`)
	//
	// ### Cost Metrics
	// - `inputCost` (number) - Input cost in USD
	// - `outputCost` (number) - Output cost in USD
	// - `totalCost` (number) - Total cost in USD
	//
	// ### Model Information
	// - `model` (string) - Provided model name (alias: `providedModelName`)
	// - `promptName` (string) - Associated prompt name
	// - `promptVersion` (number) - Associated prompt version
	//
	// ### Structured Data
	// - `metadata` (stringObject/numberObject/categoryOptions) - Metadata key-value pairs. Use `key` parameter to filter on specific metadata keys.
	//
	// ## Filter Examples
	// ```json
	// [
	//
	//	{
	//	  "type": "string",
	//	  "column": "type",
	//	  "operator": "=",
	//	  "value": "GENERATION"
	//	},
	//	{
	//	  "type": "number",
	//	  "column": "latency",
	//	  "operator": ">=",
	//	  "value": 2.5
	//	},
	//	{
	//	  "type": "stringObject",
	//	  "column": "metadata",
	//	  "key": "environment",
	//	  "operator": "=",
	//	  "value": "production"
	//	}
	//
	// ]
	// ```
	Filter *string `json:"-" url:"filter,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (o *ObservationsGetManyRequest) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetFields(fields *string) {
	o.Fields = fields
	o.require(observationsGetManyRequestFieldFields)
}

// SetExpandMetadata sets the ExpandMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetExpandMetadata(expandMetadata *string) {
	o.ExpandMetadata = expandMetadata
	o.require(observationsGetManyRequestFieldExpandMetadata)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetLimit(limit *int) {
	o.Limit = limit
	o.require(observationsGetManyRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetCursor(cursor *string) {
	o.Cursor = cursor
	o.require(observationsGetManyRequestFieldCursor)
}

// SetParseIoAsJSON sets the ParseIoAsJSON field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetParseIoAsJSON(parseIoAsJSON *bool) {
	o.ParseIoAsJSON = parseIoAsJSON
	o.require(observationsGetManyRequestFieldParseIoAsJSON)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetName(name *string) {
	o.Name = name
	o.require(observationsGetManyRequestFieldName)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetUserID(userID *string) {
	o.UserID = userID
	o.require(observationsGetManyRequestFieldUserID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetType(type_ *string) {
	o.Type = type_
	o.require(observationsGetManyRequestFieldType)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetTraceID(traceID *string) {
	o.TraceID = traceID
	o.require(observationsGetManyRequestFieldTraceID)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetLevel(level *ObservationLevel) {
	o.Level = level
	o.require(observationsGetManyRequestFieldLevel)
}

// SetParentObservationID sets the ParentObservationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetParentObservationID(parentObservationID *string) {
	o.ParentObservationID = parentObservationID
	o.require(observationsGetManyRequestFieldParentObservationID)
}

// SetEnvironment sets the Environment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetEnvironment(environment []*string) {
	o.Environment = environment
	o.require(observationsGetManyRequestFieldEnvironment)
}

// SetFromStartTime sets the FromStartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetFromStartTime(fromStartTime *time.Time) {
	o.FromStartTime = fromStartTime
	o.require(observationsGetManyRequestFieldFromStartTime)
}

// SetToStartTime sets the ToStartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetToStartTime(toStartTime *time.Time) {
	o.ToStartTime = toStartTime
	o.require(observationsGetManyRequestFieldToStartTime)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetVersion(version *string) {
	o.Version = version
	o.require(observationsGetManyRequestFieldVersion)
}

// SetFilter sets the Filter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsGetManyRequest) SetFilter(filter *string) {
	o.Filter = filter
	o.require(observationsGetManyRequestFieldFilter)
}

// An observation from the v2 API with field-group-based selection.
// Core fields are always present. Other fields are included only when their field group is requested.
var (
	observationV2FieldID                  = big.NewInt(1 << 0)
	observationV2FieldTraceID             = big.NewInt(1 << 1)
	observationV2FieldStartTime           = big.NewInt(1 << 2)
	observationV2FieldEndTime             = big.NewInt(1 << 3)
	observationV2FieldProjectID           = big.NewInt(1 << 4)
	observationV2FieldParentObservationID = big.NewInt(1 << 5)
	observationV2FieldType                = big.NewInt(1 << 6)
	observationV2FieldName                = big.NewInt(1 << 7)
	observationV2FieldLevel               = big.NewInt(1 << 8)
	observationV2FieldStatusMessage       = big.NewInt(1 << 9)
	observationV2FieldVersion             = big.NewInt(1 << 10)
	observationV2FieldEnvironment         = big.NewInt(1 << 11)
	observationV2FieldBookmarked          = big.NewInt(1 << 12)
	observationV2FieldPublic              = big.NewInt(1 << 13)
	observationV2FieldUserID              = big.NewInt(1 << 14)
	observationV2FieldSessionID           = big.NewInt(1 << 15)
	observationV2FieldCompletionStartTime = big.NewInt(1 << 16)
	observationV2FieldCreatedAt           = big.NewInt(1 << 17)
	observationV2FieldUpdatedAt           = big.NewInt(1 << 18)
	observationV2FieldInput               = big.NewInt(1 << 19)
	observationV2FieldOutput              = big.NewInt(1 << 20)
	observationV2FieldMetadata            = big.NewInt(1 << 21)
	observationV2FieldProvidedModelName   = big.NewInt(1 << 22)
	observationV2FieldInternalModelID     = big.NewInt(1 << 23)
	observationV2FieldModelParameters     = big.NewInt(1 << 24)
	observationV2FieldUsageDetails        = big.NewInt(1 << 25)
	observationV2FieldCostDetails         = big.NewInt(1 << 26)
	observationV2FieldTotalCost           = big.NewInt(1 << 27)
	observationV2FieldPromptID            = big.NewInt(1 << 28)
	observationV2FieldPromptName          = big.NewInt(1 << 29)
	observationV2FieldPromptVersion       = big.NewInt(1 << 30)
	observationV2FieldLatency             = big.NewInt(1 << 31)
	observationV2FieldTimeToFirstToken    = big.NewInt(1 << 32)
	observationV2FieldModelID             = big.NewInt(1 << 33)
)

type ObservationV2 struct {
	// The unique identifier of the observation
	ID string `json:"id" url:"id"`
	// The trace ID associated with the observation
	TraceID *string `json:"traceId,omitempty" url:"traceId,omitempty"`
	// The start time of the observation
	StartTime time.Time `json:"startTime" url:"startTime"`
	// The end time of the observation
	EndTime *time.Time `json:"endTime,omitempty" url:"endTime,omitempty"`
	// The project ID this observation belongs to
	ProjectID string `json:"projectId" url:"projectId"`
	// The parent observation ID
	ParentObservationID *string `json:"parentObservationId,omitempty" url:"parentObservationId,omitempty"`
	// The type of the observation (e.g. GENERATION, SPAN, EVENT)
	Type string `json:"type" url:"type"`
	// The name of the observation
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The level of the observation
	Level *ObservationLevel `json:"level,omitempty" url:"level,omitempty"`
	// The status message of the observation
	StatusMessage *string `json:"statusMessage,omitempty" url:"statusMessage,omitempty"`
	// The version of the observation
	Version *string `json:"version,omitempty" url:"version,omitempty"`
	// The environment from which this observation originated
	Environment *string `json:"environment,omitempty" url:"environment,omitempty"`
	// Whether the observation is bookmarked
	Bookmarked *bool `json:"bookmarked,omitempty" url:"bookmarked,omitempty"`
	// Whether the observation is public
	Public *bool `json:"public,omitempty" url:"public,omitempty"`
	// The user ID associated with the observation
	UserID *string `json:"userId,omitempty" url:"userId,omitempty"`
	// The session ID associated with the observation
	SessionID *string `json:"sessionId,omitempty" url:"sessionId,omitempty"`
	// The completion start time of the observation
	CompletionStartTime *time.Time `json:"completionStartTime,omitempty" url:"completionStartTime,omitempty"`
	// The creation timestamp of the observation
	CreatedAt *time.Time `json:"createdAt,omitempty" url:"createdAt,omitempty"`
	// The last update timestamp of the observation
	UpdatedAt *time.Time `json:"updatedAt,omitempty" url:"updatedAt,omitempty"`
	// The input data of the observation
	Input any `json:"input,omitempty" url:"input,omitempty"`
	// The output data of the observation
	Output any `json:"output,omitempty" url:"output,omitempty"`
	// Additional metadata of the observation
	Metadata any `json:"metadata,omitempty" url:"metadata,omitempty"`
	// The model name as provided by the user
	ProvidedModelName *string `json:"providedModelName,omitempty" url:"providedModelName,omitempty"`
	// The internal model ID matched by Langfuse
	InternalModelID *string `json:"internalModelId,omitempty" url:"internalModelId,omitempty"`
	// The parameters of the model used for the observation
	ModelParameters any `json:"modelParameters,omitempty" url:"modelParameters,omitempty"`
	// The usage details of the observation. Key is the usage metric name, value is the number of units consumed.
	UsageDetails map[string]*int `json:"usageDetails,omitempty" url:"usageDetails,omitempty"`
	// The cost details of the observation. Key is the cost metric name, value is the cost in USD.
	CostDetails map[string]*float64 `json:"costDetails,omitempty" url:"costDetails,omitempty"`
	// The total cost of the observation in USD
	TotalCost *float64 `json:"totalCost,omitempty" url:"totalCost,omitempty"`
	// The prompt ID associated with the observation
	PromptID *string `json:"promptId,omitempty" url:"promptId,omitempty"`
	// The prompt name associated with the observation
	PromptName *string `json:"promptName,omitempty" url:"promptName,omitempty"`
	// The prompt version associated with the observation
	PromptVersion *int `json:"promptVersion,omitempty" url:"promptVersion,omitempty"`
	// The latency in seconds
	Latency *float64 `json:"latency,omitempty" url:"latency,omitempty"`
	// The time to first token in seconds
	TimeToFirstToken *float64 `json:"timeToFirstToken,omitempty" url:"timeToFirstToken,omitempty"`
	// The matched model ID
	ModelID *string `json:"modelId,omitempty" url:"modelId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *ObservationV2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ObservationV2) GetTraceID() *string {
	if o == nil {
		return nil
	}
	return o.TraceID
}

func (o *ObservationV2) GetStartTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartTime
}

func (o *ObservationV2) GetEndTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *ObservationV2) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *ObservationV2) GetParentObservationID() *string {
	if o == nil {
		return nil
	}
	return o.ParentObservationID
}

func (o *ObservationV2) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *ObservationV2) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ObservationV2) GetLevel() *ObservationLevel {
	if o == nil {
		return nil
	}
	return o.Level
}

func (o *ObservationV2) GetStatusMessage() *string {
	if o == nil {
		return nil
	}
	return o.StatusMessage
}

func (o *ObservationV2) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *ObservationV2) GetEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *ObservationV2) GetBookmarked() *bool {
	if o == nil {
		return nil
	}
	return o.Bookmarked
}

func (o *ObservationV2) GetPublic() *bool {
	if o == nil {
		return nil
	}
	return o.Public
}

func (o *ObservationV2) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *ObservationV2) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *ObservationV2) GetCompletionStartTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.CompletionStartTime
}

func (o *ObservationV2) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *ObservationV2) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *ObservationV2) GetInput() any {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *ObservationV2) GetOutput() any {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *ObservationV2) GetMetadata() any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *ObservationV2) GetProvidedModelName() *string {
	if o == nil {
		return nil
	}
	return o.ProvidedModelName
}

func (o *ObservationV2) GetInternalModelID() *string {
	if o == nil {
		return nil
	}
	return o.InternalModelID
}

func (o *ObservationV2) GetModelParameters() any {
	if o == nil {
		return nil
	}
	return o.ModelParameters
}

func (o *ObservationV2) GetUsageDetails() map[string]*int {
	if o == nil {
		return nil
	}
	return o.UsageDetails
}

func (o *ObservationV2) GetCostDetails() map[string]*float64 {
	if o == nil {
		return nil
	}
	return o.CostDetails
}

func (o *ObservationV2) GetTotalCost() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalCost
}

func (o *ObservationV2) GetPromptID() *string {
	if o == nil {
		return nil
	}
	return o.PromptID
}

func (o *ObservationV2) GetPromptName() *string {
	if o == nil {
		return nil
	}
	return o.PromptName
}

func (o *ObservationV2) GetPromptVersion() *int {
	if o == nil {
		return nil
	}
	return o.PromptVersion
}

func (o *ObservationV2) GetLatency() *float64 {
	if o == nil {
		return nil
	}
	return o.Latency
}

func (o *ObservationV2) GetTimeToFirstToken() *float64 {
	if o == nil {
		return nil
	}
	return o.TimeToFirstToken
}

func (o *ObservationV2) GetModelID() *string {
	if o == nil {
		return nil
	}
	return o.ModelID
}

func (o *ObservationV2) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *ObservationV2) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetID(id string) {
	o.ID = id
	o.require(observationV2FieldID)
}

// SetTraceID sets the TraceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetTraceID(traceID *string) {
	o.TraceID = traceID
	o.require(observationV2FieldTraceID)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetStartTime(startTime time.Time) {
	o.StartTime = startTime
	o.require(observationV2FieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetEndTime(endTime *time.Time) {
	o.EndTime = endTime
	o.require(observationV2FieldEndTime)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetProjectID(projectID string) {
	o.ProjectID = projectID
	o.require(observationV2FieldProjectID)
}

// SetParentObservationID sets the ParentObservationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetParentObservationID(parentObservationID *string) {
	o.ParentObservationID = parentObservationID
	o.require(observationV2FieldParentObservationID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetType(type_ string) {
	o.Type = type_
	o.require(observationV2FieldType)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetName(name *string) {
	o.Name = name
	o.require(observationV2FieldName)
}

// SetLevel sets the Level field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetLevel(level *ObservationLevel) {
	o.Level = level
	o.require(observationV2FieldLevel)
}

// SetStatusMessage sets the StatusMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetStatusMessage(statusMessage *string) {
	o.StatusMessage = statusMessage
	o.require(observationV2FieldStatusMessage)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetVersion(version *string) {
	o.Version = version
	o.require(observationV2FieldVersion)
}

// SetEnvironment sets the Environment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetEnvironment(environment *string) {
	o.Environment = environment
	o.require(observationV2FieldEnvironment)
}

// SetBookmarked sets the Bookmarked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetBookmarked(bookmarked *bool) {
	o.Bookmarked = bookmarked
	o.require(observationV2FieldBookmarked)
}

// SetPublic sets the Public field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetPublic(public *bool) {
	o.Public = public
	o.require(observationV2FieldPublic)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetUserID(userID *string) {
	o.UserID = userID
	o.require(observationV2FieldUserID)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetSessionID(sessionID *string) {
	o.SessionID = sessionID
	o.require(observationV2FieldSessionID)
}

// SetCompletionStartTime sets the CompletionStartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetCompletionStartTime(completionStartTime *time.Time) {
	o.CompletionStartTime = completionStartTime
	o.require(observationV2FieldCompletionStartTime)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetCreatedAt(createdAt *time.Time) {
	o.CreatedAt = createdAt
	o.require(observationV2FieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetUpdatedAt(updatedAt *time.Time) {
	o.UpdatedAt = updatedAt
	o.require(observationV2FieldUpdatedAt)
}

// SetInput sets the Input field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetInput(input any) {
	o.Input = input
	o.require(observationV2FieldInput)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetOutput(output any) {
	o.Output = output
	o.require(observationV2FieldOutput)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetMetadata(metadata any) {
	o.Metadata = metadata
	o.require(observationV2FieldMetadata)
}

// SetProvidedModelName sets the ProvidedModelName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetProvidedModelName(providedModelName *string) {
	o.ProvidedModelName = providedModelName
	o.require(observationV2FieldProvidedModelName)
}

// SetInternalModelID sets the InternalModelID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetInternalModelID(internalModelID *string) {
	o.InternalModelID = internalModelID
	o.require(observationV2FieldInternalModelID)
}

// SetModelParameters sets the ModelParameters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetModelParameters(modelParameters any) {
	o.ModelParameters = modelParameters
	o.require(observationV2FieldModelParameters)
}

// SetUsageDetails sets the UsageDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetUsageDetails(usageDetails map[string]*int) {
	o.UsageDetails = usageDetails
	o.require(observationV2FieldUsageDetails)
}

// SetCostDetails sets the CostDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetCostDetails(costDetails map[string]*float64) {
	o.CostDetails = costDetails
	o.require(observationV2FieldCostDetails)
}

// SetTotalCost sets the TotalCost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetTotalCost(totalCost *float64) {
	o.TotalCost = totalCost
	o.require(observationV2FieldTotalCost)
}

// SetPromptID sets the PromptID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetPromptID(promptID *string) {
	o.PromptID = promptID
	o.require(observationV2FieldPromptID)
}

// SetPromptName sets the PromptName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetPromptName(promptName *string) {
	o.PromptName = promptName
	o.require(observationV2FieldPromptName)
}

// SetPromptVersion sets the PromptVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetPromptVersion(promptVersion *int) {
	o.PromptVersion = promptVersion
	o.require(observationV2FieldPromptVersion)
}

// SetLatency sets the Latency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetLatency(latency *float64) {
	o.Latency = latency
	o.require(observationV2FieldLatency)
}

// SetTimeToFirstToken sets the TimeToFirstToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetTimeToFirstToken(timeToFirstToken *float64) {
	o.TimeToFirstToken = timeToFirstToken
	o.require(observationV2FieldTimeToFirstToken)
}

// SetModelID sets the ModelID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationV2) SetModelID(modelID *string) {
	o.ModelID = modelID
	o.require(observationV2FieldModelID)
}

func (o *ObservationV2) UnmarshalJSON(data []byte) error {
	type embed ObservationV2
	var unmarshaler = struct {
		embed
		StartTime           *internal.DateTime `json:"startTime"`
		EndTime             *internal.DateTime `json:"endTime,omitempty"`
		CompletionStartTime *internal.DateTime `json:"completionStartTime,omitempty"`
		CreatedAt           *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt           *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed: embed(*o),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*o = ObservationV2(unmarshaler.embed)
	o.StartTime = unmarshaler.StartTime.Time()
	o.EndTime = unmarshaler.EndTime.TimePtr()
	o.CompletionStartTime = unmarshaler.CompletionStartTime.TimePtr()
	o.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	o.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *ObservationV2) MarshalJSON() ([]byte, error) {
	type embed ObservationV2
	var marshaler = struct {
		embed
		StartTime           *internal.DateTime `json:"startTime"`
		EndTime             *internal.DateTime `json:"endTime,omitempty"`
		CompletionStartTime *internal.DateTime `json:"completionStartTime,omitempty"`
		CreatedAt           *internal.DateTime `json:"createdAt,omitempty"`
		UpdatedAt           *internal.DateTime `json:"updatedAt,omitempty"`
	}{
		embed:               embed(*o),
		StartTime:           internal.NewDateTime(o.StartTime),
		EndTime:             internal.NewOptionalDateTime(o.EndTime),
		CompletionStartTime: internal.NewOptionalDateTime(o.CompletionStartTime),
		CreatedAt:           internal.NewOptionalDateTime(o.CreatedAt),
		UpdatedAt:           internal.NewOptionalDateTime(o.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *ObservationV2) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Metadata for cursor-based pagination
var (
	observationsV2MetaFieldCursor = big.NewInt(1 << 0)
)

type ObservationsV2Meta struct {
	// Base64-encoded cursor to use for retrieving the next page. If not present, there are no more results.
	Cursor *string `json:"cursor,omitempty" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *ObservationsV2Meta) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ObservationsV2Meta) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *ObservationsV2Meta) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsV2Meta) SetCursor(cursor *string) {
	o.Cursor = cursor
	o.require(observationsV2MetaFieldCursor)
}

func (o *ObservationsV2Meta) UnmarshalJSON(data []byte) error {
	type unmarshaler ObservationsV2Meta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = ObservationsV2Meta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *ObservationsV2Meta) MarshalJSON() ([]byte, error) {
	type embed ObservationsV2Meta
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *ObservationsV2Meta) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Response containing observations with field-group-based filtering and cursor-based pagination.
//
// The `data` array contains observation objects with only the requested field groups included.
// Use the `cursor` in `meta` to retrieve the next page of results.
var (
	observationsV2ResponseFieldData = big.NewInt(1 << 0)
	observationsV2ResponseFieldMeta = big.NewInt(1 << 1)
)

type ObservationsV2Response struct {
	// Array of observation objects. Fields included depend on the `fields` parameter in the request.
	Data []*ObservationV2    `json:"data" url:"data"`
	Meta *ObservationsV2Meta `json:"meta" url:"meta"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *ObservationsV2Response) GetData() []*ObservationV2 {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ObservationsV2Response) GetMeta() *ObservationsV2Meta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *ObservationsV2Response) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *ObservationsV2Response) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsV2Response) SetData(data []*ObservationV2) {
	o.Data = data
	o.require(observationsV2ResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *ObservationsV2Response) SetMeta(meta *ObservationsV2Meta) {
	o.Meta = meta
	o.require(observationsV2ResponseFieldMeta)
}

func (o *ObservationsV2Response) UnmarshalJSON(data []byte) error {
	type unmarshaler ObservationsV2Response
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = ObservationsV2Response(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *ObservationsV2Response) MarshalJSON() ([]byte, error) {
	type embed ObservationsV2Response
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *ObservationsV2Response) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
