// Code generated by Fern. DO NOT EDIT.

package annotationqueues_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	langfuse "github.com/corysm1th/langfuse-go"
	client "github.com/corysm1th/langfuse-go/client"
	option "github.com/corysm1th/langfuse-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAnnotationqueuesListqueuesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesListQueuesRequest{}
	_, invocationErr := client.Annotationqueues.Listqueues(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesListqueuesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesListqueuesWithWireMock", "GET", "/api/public/annotation-queues", nil, 1)
}

func TestAnnotationqueuesCreatequeueWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.CreateAnnotationQueueRequest{
		Name: "name",
		ScoreConfigIDs: []string{
			"scoreConfigIds",
		},
	}
	_, invocationErr := client.Annotationqueues.Createqueue(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesCreatequeueWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesCreatequeueWithWireMock", "POST", "/api/public/annotation-queues", nil, 1)
}

func TestAnnotationqueuesGetqueueWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesGetQueueRequest{
		QueueID: "queueId",
	}
	_, invocationErr := client.Annotationqueues.Getqueue(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesGetqueueWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesGetqueueWithWireMock", "GET", "/api/public/annotation-queues/queueId", nil, 1)
}

func TestAnnotationqueuesListqueueitemsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesListQueueItemsRequest{
		QueueID: "queueId",
	}
	_, invocationErr := client.Annotationqueues.Listqueueitems(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesListqueueitemsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesListqueueitemsWithWireMock", "GET", "/api/public/annotation-queues/queueId/items", nil, 1)
}

func TestAnnotationqueuesCreatequeueitemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.CreateAnnotationQueueItemRequest{
		QueueID:    "queueId",
		ObjectID:   "objectId",
		ObjectType: langfuse.AnnotationQueueObjectTypeTrace,
	}
	_, invocationErr := client.Annotationqueues.Createqueueitem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesCreatequeueitemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesCreatequeueitemWithWireMock", "POST", "/api/public/annotation-queues/queueId/items", nil, 1)
}

func TestAnnotationqueuesGetqueueitemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesGetQueueItemRequest{
		QueueID: "queueId",
		ItemID:  "itemId",
	}
	_, invocationErr := client.Annotationqueues.Getqueueitem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesGetqueueitemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesGetqueueitemWithWireMock", "GET", "/api/public/annotation-queues/queueId/items/itemId", nil, 1)
}

func TestAnnotationqueuesDeletequeueitemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesDeleteQueueItemRequest{
		QueueID: "queueId",
		ItemID:  "itemId",
	}
	_, invocationErr := client.Annotationqueues.Deletequeueitem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesDeletequeueitemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesDeletequeueitemWithWireMock", "DELETE", "/api/public/annotation-queues/queueId/items/itemId", nil, 1)
}

func TestAnnotationqueuesUpdatequeueitemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.UpdateAnnotationQueueItemRequest{
		QueueID: "queueId",
		ItemID:  "itemId",
	}
	_, invocationErr := client.Annotationqueues.Updatequeueitem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesUpdatequeueitemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesUpdatequeueitemWithWireMock", "PATCH", "/api/public/annotation-queues/queueId/items/itemId", nil, 1)
}

func TestAnnotationqueuesCreatequeueassignmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesCreateQueueAssignmentRequest{
		QueueID: "queueId",
		Body: &langfuse.AnnotationQueueAssignmentRequest{
			UserID: "userId",
		},
	}
	_, invocationErr := client.Annotationqueues.Createqueueassignment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesCreatequeueassignmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesCreatequeueassignmentWithWireMock", "POST", "/api/public/annotation-queues/queueId/assignments", nil, 1)
}

func TestAnnotationqueuesDeletequeueassignmentWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.AnnotationQueuesDeleteQueueAssignmentRequest{
		QueueID: "queueId",
		Body: &langfuse.AnnotationQueueAssignmentRequest{
			UserID: "userId",
		},
	}
	_, invocationErr := client.Annotationqueues.Deletequeueassignment(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAnnotationqueuesDeletequeueassignmentWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAnnotationqueuesDeletequeueassignmentWithWireMock", "DELETE", "/api/public/annotation-queues/queueId/assignments", nil, 1)
}
