// Code generated by Fern. DO NOT EDIT.

package media

import (
	context "context"

	langfuse "github.com/corysm1th/langfuse-go"
	core "github.com/corysm1th/langfuse-go/core"
	internal "github.com/corysm1th/langfuse-go/internal"
	option "github.com/corysm1th/langfuse-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get a media record
func (c *Client) Get(
	ctx context.Context,
	request *langfuse.MediaGetRequest,
	opts ...option.RequestOption,
) (*langfuse.GetMediaResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Patch a media record
func (c *Client) Patch(
	ctx context.Context,
	request *langfuse.PatchMediaBody,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Patch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get a presigned upload URL for a media record
func (c *Client) Getuploadurl(
	ctx context.Context,
	request *langfuse.GetMediaUploadURLRequest,
	opts ...option.RequestOption,
) (*langfuse.GetMediaUploadURLResponse, error) {
	response, err := c.WithRawResponse.Getuploadurl(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
