// Code generated by Fern. DO NOT EDIT.

package blobstorageintegrations

import (
	context "context"

	langfuse "github.com/corysm1th/langfuse-go"
	core "github.com/corysm1th/langfuse-go/core"
	internal "github.com/corysm1th/langfuse-go/internal"
	option "github.com/corysm1th/langfuse-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get all blob storage integrations for the organization (requires organization-scoped API key)
func (c *Client) Getblobstorageintegrations(
	ctx context.Context,
	opts ...option.RequestOption,
) (*langfuse.BlobStorageIntegrationsResponse, error) {
	response, err := c.WithRawResponse.Getblobstorageintegrations(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create or update a blob storage integration for a specific project (requires organization-scoped API key). The configuration is validated by performing a test upload to the bucket.
func (c *Client) Upsertblobstorageintegration(
	ctx context.Context,
	request *langfuse.CreateBlobStorageIntegrationRequest,
	opts ...option.RequestOption,
) (*langfuse.BlobStorageIntegrationResponse, error) {
	response, err := c.WithRawResponse.Upsertblobstorageintegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get the sync status of a blob storage integration by integration ID (requires organization-scoped API key)
func (c *Client) Getblobstorageintegrationstatus(
	ctx context.Context,
	request *langfuse.BlobStorageIntegrationsGetBlobStorageIntegrationStatusRequest,
	opts ...option.RequestOption,
) (*langfuse.BlobStorageIntegrationStatusResponse, error) {
	response, err := c.WithRawResponse.Getblobstorageintegrationstatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a blob storage integration by ID (requires organization-scoped API key)
func (c *Client) Deleteblobstorageintegration(
	ctx context.Context,
	request *langfuse.BlobStorageIntegrationsDeleteBlobStorageIntegrationRequest,
	opts ...option.RequestOption,
) (*langfuse.BlobStorageIntegrationDeletionResponse, error) {
	response, err := c.WithRawResponse.Deleteblobstorageintegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
