// Code generated by Fern. DO NOT EDIT.

package datasetrunitems

import (
	context "context"

	langfuse "github.com/corysm1th/langfuse-go"
	core "github.com/corysm1th/langfuse-go/core"
	internal "github.com/corysm1th/langfuse-go/internal"
	option "github.com/corysm1th/langfuse-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List dataset run items
func (c *Client) List(
	ctx context.Context,
	request *langfuse.DatasetRunItemsListRequest,
	opts ...option.RequestOption,
) (*langfuse.PaginatedDatasetRunItems, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a dataset run item
func (c *Client) Create(
	ctx context.Context,
	request *langfuse.CreateDatasetRunItemRequest,
	opts ...option.RequestOption,
) (*langfuse.DatasetRunItem, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
