// Code generated by Fern. DO NOT EDIT.

package legacyscorev1

import (
	context "context"

	langfuse "github.com/corysm1th/langfuse-go"
	core "github.com/corysm1th/langfuse-go/core"
	internal "github.com/corysm1th/langfuse-go/internal"
	option "github.com/corysm1th/langfuse-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Create a score (supports both trace and session scores)
func (c *Client) LegacyScoreV1Create(
	ctx context.Context,
	request *langfuse.LegacyCreateScoreRequest,
	opts ...option.RequestOption,
) (*langfuse.LegacyCreateScoreResponse, error) {
	response, err := c.WithRawResponse.LegacyScoreV1Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a score (supports both trace and session scores)
func (c *Client) LegacyScoreV1Delete(
	ctx context.Context,
	request *langfuse.LegacyScoreV1DeleteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.LegacyScoreV1Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
