// Code generated by Fern. DO NOT EDIT.

package projects_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	langfuse "github.com/corysm1th/langfuse-go"
	client "github.com/corysm1th/langfuse-go/client"
	option "github.com/corysm1th/langfuse-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestProjectsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	_, invocationErr := client.Projects.Get(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsGetWithWireMock", "GET", "/api/public/projects", nil, 1)
}

func TestProjectsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsCreateRequest{
		Name:      "name",
		Retention: 1,
	}
	_, invocationErr := client.Projects.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsCreateWithWireMock", "POST", "/api/public/projects", nil, 1)
}

func TestProjectsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsUpdateRequest{
		ProjectID: "projectId",
		Name:      "name",
	}
	_, invocationErr := client.Projects.Update(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsUpdateWithWireMock", "PUT", "/api/public/projects/projectId", nil, 1)
}

func TestProjectsDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsDeleteRequest{
		ProjectID: "projectId",
	}
	_, invocationErr := client.Projects.Delete(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsDeleteWithWireMock", "DELETE", "/api/public/projects/projectId", nil, 1)
}

func TestProjectsGetapikeysWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsGetAPIKeysRequest{
		ProjectID: "projectId",
	}
	_, invocationErr := client.Projects.Getapikeys(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsGetapikeysWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsGetapikeysWithWireMock", "GET", "/api/public/projects/projectId/apiKeys", nil, 1)
}

func TestProjectsCreateapikeyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsCreateAPIKeyRequest{
		ProjectID: "projectId",
	}
	_, invocationErr := client.Projects.Createapikey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsCreateapikeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsCreateapikeyWithWireMock", "POST", "/api/public/projects/projectId/apiKeys", nil, 1)
}

func TestProjectsDeleteapikeyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewLangfuseClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &langfuse.ProjectsDeleteAPIKeyRequest{
		ProjectID: "projectId",
		APIKeyID:  "apiKeyId",
	}
	_, invocationErr := client.Projects.Deleteapikey(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestProjectsDeleteapikeyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestProjectsDeleteapikeyWithWireMock", "DELETE", "/api/public/projects/projectId/apiKeys/apiKeyId", nil, 1)
}
