// Code generated by Fern. DO NOT EDIT.

package models

import (
	context "context"

	langfuse "github.com/corysm1th/langfuse-go"
	core "github.com/corysm1th/langfuse-go/core"
	internal "github.com/corysm1th/langfuse-go/internal"
	option "github.com/corysm1th/langfuse-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Get all models
func (c *Client) List(
	ctx context.Context,
	request *langfuse.ModelsListRequest,
	opts ...option.RequestOption,
) (*langfuse.PaginatedModels, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a model
func (c *Client) Create(
	ctx context.Context,
	request *langfuse.CreateModelRequest,
	opts ...option.RequestOption,
) (*langfuse.Model, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get a model
func (c *Client) Get(
	ctx context.Context,
	request *langfuse.ModelsGetRequest,
	opts ...option.RequestOption,
) (*langfuse.Model, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
func (c *Client) Delete(
	ctx context.Context,
	request *langfuse.ModelsDeleteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
